name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: gradle init
    - run: gradle updateDaemonJvm
    - run: gradle wrapper
    - run: gradle tasks --all
    - run: pwd
