name: Run smoke tests

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - uses: actions/checkout@v23
    - name: Set up JDK 23
      uses: actions/setup-java@v23
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew clean test

    - name: Copy History
      uses: actions/checkout@v2
      if: always()
      with:
        ref: test-3
        path: test-3

    - name: Build Report
      uses: simple-elf/allure-report-action@v1.10
      if: always()
      with:
        allure_results: build/allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Publish Report
      if: always()
      uses: peaceiris/actions-test-3@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: test-3
        PUBLISH_DIR: allure-history
