name: Run smoke tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Install Allure Commandline
      run: |
        sudo apt-get update && sudo apt-get install -y allure

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Check contents of build directory
      if: always()
      run: ls -R build
      
    - name: Upload Allure Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        allure_results: build/allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Publish Report
      if: always()
      uses: peaceiris/actions-report@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: report
        PUBLISH_DIR: allure-history
